### PR TITLE
Rewrite code generation to javapoet

### PR DESCRIPTION
**Pull request by ekursakov**
- [x] Rewrite ViewStateProviderClassGenerator
- [x] Rewrite ViewStateClassGenerator
- [x] Rewrite PresenterBinderClassGenerator
- [x] Rewrite MoxyReflectorGenerator
- [x] Pass javapoet classes for type names to MoxyReflectorGenerator
- [x] Remove ClassGeneratingParams and change it to JavaFile from javapoet
- [x] Fix bugs from tests in #190

### CODE REVIEW

**Comment by Macarse** [comment]
status?

**Comment by senneco** [comment]
Hi @Macarse great job! Currently I think how to test this very big PR %) Have you any ideas?)

**Comment by Macarse** [comment]
@senneco I didn't do the work

**Comment by xanderblinov** [comment]
@senneco it's not real by writing tests using comparing input with expected input, because javapoet has another formatting style. We have only one chance by comparing bytecode of input and expected input

**Comment by senneco** [comment]
@Macarse ouch =) @ekursakov great job! Currently I'm thinking how to test this very big PR %) Have you any ideas?)

I can't approve PR without any guaranties that this code works correctly =(

**Comment by ekursakov** [comment]
Hi! Sorry for my long absence, I did't have enough time to return to this PR.
As for tests I think that they should compare compiler output with excepted result.
Assertions from google compile-testing are parsing source code and comparing AST only. So formatting won't be a problem.
I will try to write some tests in the coming days and I'll update PR.

**Comment by ekursakov** [comment]
I created some tests for moxy compiler in separate PR: https://github.com/Arello-Mobile/Moxy/pull/170.
Generated files compared in bytecode so tests should work both with old and new compiler.

**Comment by senneco** [comment]
Hi @ekursakov!

I planned to make more tests before apply this PR. But I haven't time =( Could you make more test? We need those:
1. More generics tests (generic classes, generic methods, wildcards, etc)
2. Command's strategies joining between view interface extensions.

If you need, I can explain these points.

Hope for you have ability to make it =)

**Comment by ekursakov** [comment]
I wrote some more compiler tests in #190 and discovered some bugs in this implementation :) So will try to fix it in near future.

**Comment by xanderblinov** [comment]
@ekursakov great job! So now this implementation still have some bugs and doesn't ready for release?

**Comment by ekursakov** [comment]
@xanderblinov Forgot to write, I fixed bugs which discovered by tests from #190, now it passes all tests as well as old moxy-compiler (#181 still needs to be fixed separately).
Of course there may still be bugs with complex cases, but on example apps it works fine.

**Pull request merged**
