### PR TITLE
Strategy Trace & Remove

### LINKED ISSUE #28: StateStrategy for "clearable" ViewCommands
Let's examine this use-case: presenter adds group of markers to map, removes some of them afterwards, some - not. This process may repeate multitude of times, then orientation changes, and ViewState is reapplied to newly attached View. From user perspective it would be lengthy process of repeating all actions user had done, while he just needs markers which "survived" removal. 

To solve this issue it would be great to add one more `StateStrategy` - `TraceStrategy` and `ClearStrategy` (counterpart)

For example, let's have a method:

```
public class MapView implements MvpView {
   /*
   * Some other code
   */
   private int counter = 0;

   @StateStrategy(value = TraceStrategy.class, tag = "addMarker")
   int addMarker(double lat, double lon) {
      // ...
      return counter++;
   }
}
```
In result of this `ViewCommand` on top of `ViewCommand` stack new `ViewCommand` should be added with tag = "addMarker0". Running this command again will result in `ViewCommand` with tag = "addMarker1" and so on. Number is value returned by method (more generally - `toString()` of returned `Object`).

Now counterpart for `addMarker` will be 
```
public class MapView implements MvpView {
   /*
   * Some other code
   */
   private int counter = 1; // Affected by addMarker()

   @StateStrategy(value = ClearStrategy.class, tag = "addMarker")
   int removeMarker(int id) {
      // ...
      return --counter;
   }
}
```
This `ViewCommand` appends to tag returned value than searches `ViewCommand` with tag whose value is, for instance, "addMarker0", removes it and **does not** put itself in stack.

Drawbacks of this approach are:

- Proguard should handle tag of ClearStrategy appropriately

- remove* methods shoud return its argument

P.S. 
If there is no return value required, for example, just one marker can be added, than `TraceStrategy` and `ClearStrategy` should also take care of this.

P.P.S
Issue instead of PR because I think there is discussion part in this issue.

### PR DESCRIPTION
**Pull request by alextel69**
Closes #28

### CODE REVIEW

**Comment by terrakok** [comment]
Are you sure that these strategies are necessary to add them to the library? May be Gist?

**Comment by alextel69** [comment]
@terrakok For instance, you may show fragment in `showFragment`, then hide it by tag supplied with `hideFragment` because of some event in model. However, due to async nature of fragment transaction, reapplying these actions may result in `NPE`, because in `hideFragment` method fragment may not exist.

There was question about this [here](https://habrahabr.ru/post/276189/#comment_8801515), also was required in my project.

These were my concerns.

**Comment by alextel69** [comment]
@xanderblinov could you tell how to access field in generic ViewCommand without Reflection?

**Comment by senneco** [comment]
@alextel69 currenly generated ViewCommand classes are public with public fields. And you can get access to them in your code. It's available if you use `apt` instead of `provided`, ofcourse. Then you shouldn't use reflection. Simple cast command to required Command-class.

**Comment by alextel69** [comment]
@senneco thanks for clarification. I wanted to create solution that not just me will use, but anyone else who faces task to remove ViewCommands from stack, w/o any explicit cast, thus reflection is needed, I suppose.

**Comment by alextel69** [comment]
@senneco created [gist](https://gist.github.com/alextel69/ec1ba395522fb76f206ed32fa55d980f) from this PR for supposed Moxy cookbook

**Comment by alextel69** [comment]
@xanderblinov apparently, on execution of this strategy, `NoSuchFieldException` will be thrown.
BUT! I specifically mention in Javadoc of both `TraceStrategy` and `RemoveStrategy` that

> Enforces contract: calling method should have  parameter<? extends Object> which is called "id". 

If you know better way to hook to id field of generic `ViewCommand`, I would gladly introduce it in my Strategies.

**Comment by xanderblinov** [comment]
@alextel69 Just add an interface with method getId for your commands. So checking command instance of this interface is cheep. Reflection is very expensive operation, especially for operation on main thread

**Comment by alextel69** [comment]
@xanderblinov as far as I understand, incoming `List<ViewCommand>` in `beforeApply()` in `StateStrategy` class contains `ViewCommand`s that are represented in form `MapView$$State.AddMarkerCommand`, for instance, that in turn represent [concrete methods from concrete views](https://github.com/Arello-Mobile/Moxy/issues/28#issuecomment-253738318). Parameters of method of view are saved as fields in this object.

Also, inside `MvpPresenter` you have proxy `getViewState().addMarker()` that actually saves method to list of commands.

Except from this, what are other options to control how calls to view's commands are saved? Annotation processor creates these `SomeView$$State.doSmthCommand()` `ViewCommand`s. Where is place to cast or force it to implement, say, some `IdCommand` interface?

**Comment by alextel69** [comment]
@senneco @xanderblinov any comment on [this](https://github.com/Arello-Mobile/Moxy/pull/29#issuecomment-257076005)?

**Pull request closed without merging**
